### PR TITLE
updating VS code section

### PR DESCRIPTION
**Pull request by JohanBester**
Hi Folks,
I had to make a change to the VS code section.
Could you please review and let me know if we can merge this.
Thanks!

### CODE REVIEW

**Review by dadler89 — APPROVED** [review]

**Comment by H-Matzy** [comment]
Sorry for the confusion, is there any particular reason I'm now included in
these emails? This is Hayden from the April cohort.

**Comment by H-Matzy** [comment]
Disregard, it looks like because I followed the repository on GitHub I get email notifications on comments.

**Review by cbrantley4 — COMMENTED** [review]
I'm with Matt -- why the debug files?

**Review by cbrantley4 — APPROVED** [review]
Looks good.

**Review by matsinet — APPROVED** [review]
👍

**Review by dadler89 — APPROVED** [review]

**Pull request merged**
