### PR TITLE
SC-263 router data from page to view, hasOwnProperty, and conditional hooks

### PR DESCRIPTION
**Pull request by H-Matzy**

### CODE REVIEW

**Comment by H-Matzy** [comment]
Hey everyone, had to resolve a merge request and haven't had to do that often so double check that it looks good. The issue I ran into was every student I came across had issues with their routers based on the param data having a view attribute and no page attribute, so accessing params.data.page resulted in undefined. I made changes in the curriculum to hopefully resolve this. It could have been either page or view but just needed consistency, I figured view made more sense as it follows the MVC naming convention

**Review by JohanBester — APPROVED** [review]
As I understand it, this looks good to me.

**Review by cbrantley4 — APPROVED** [review]
Merge it

**Review by matsinet — CHANGES_REQUESTED** [review]

**Comment by H-Matzy** [comment]
That was the issue I fixed, the keys in store did not match the keys accessed in router

**Comment by H-Matzy** [comment]
@matsinet the params.data.page is trying to access a property that is not in the store view, because it is named view in store

**Pull request closed without merging**
