### PR TITLE
359 update section 5 homework to no longer reference 52 material

### PR DESCRIPTION
**Pull request by mjwebb1993**
This issue was expanded to not only delete the JS Classes & Constructors Practice homework section, but it also added Homework Set Up steps and gave more specific instructions on how the Andre the Giant and JS Array Methods Practice sections should be set up.

### CODE REVIEW

**Comment by mjwebb1993** [comment]
Somehow edits to 4.1 got in there, will fix

**Comment by mjwebb1993** [comment]
No longer pushing to Master as it was also including changes on other PRs from 4.2

**Review by drod1107 — COMMENTED** [review]
Looks great! Only notes I have are:
Typo line 54 - "the do the following" should be "then do"
Suggestion: Line 65 mentions recommending copy pasting some pre-written rules in to get started. It may be wise to clarify from which sources it's acceptable to harvest that code, so they realize we mean from that file, not from the internet at large.

Didn't see anything else, and thanks for thinking to do this!

**Review by JohanBester — DISMISSED** [review]
Looks good to my one eye :)

**Review by matsinet — APPROVED** [review]
I agree with @drod1107 comments, once implemented, I approve

**Comment by mjwebb1993** [comment]
Thanks for the recommendations, I fixed the typo on line 54 and rewrote the "TIP" entirely. This is now how it reads:

`> TIP: In order to make sure your media query is functioning properly (i.e, the query triggers when expected), set up a simple css property inside your media query that changes the background color to blue *before* you attempt to fix the styling. Use your dev tools in the browser to confirm that the background changes to blue when expected (iPhone 6/7/8 view) and THEN start working on the fixes. Don't forget to remove the background color property you made to test your media query!`

**Review by matsinet — APPROVED** [review]

**Pull request merged**
